services:
  - type: web
    name: license-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: ADMIN_PANEL_URL
        value: https://grade-management-admin.vercel.app
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: license-server
